=== AntonioMC12/DAM/1º/LM/xml/EjercicioExamen/Ejercicio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="portes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="recepcion" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="producto" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="cantidad" type="tipoCantidad" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="codigoreceptor" type="tipoCodigoReceptor" maxOccurs="1"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="entrega" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="transportista" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="distancia" type="tipoUnidad"/>
                        </xs:sequence>
                        <xs:attribute name="coste" type="tipoCoste" use="required" />
                        <xs:attribute name="receptor" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipoCantidad">
        <xs:restriction base="xs:float">
            <xs:minExclusive value="0"></xs:minExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCodigoReceptor">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[a-zA-Z]{3}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoTransportista">
        <xs:restriction base="xs:string">
            <xs:enumeration value="T1"></xs:enumeration>
            <xs:enumeration value="T2"></xs:enumeration>
            <xs:enumeration value="T3"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipoUnidad">
        <xs:simpleContent>
            <xs:extension base="tipoDistancia">
                <xs:attribute name="unidad" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="tipoDistancia">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"></xs:minExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoCoste">
        <xs:restriction base="xs:integer">
            <xs:minExclusive value="0"></xs:minExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="as">
        <xs:attribute name="hola" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="estanteria[1-14]"></xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== AntonioMC12/DAM/1º/LM/xml/EjercicioExamen/Ejercicio.xml
<?xml version="1.0" encoding="UTF-8"?>
<portes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio.xsd">
    <recepcion>
        <producto>macarrones</producto>
        <cantidad>10.5</cantidad>
        <codigoreceptor>123-aBc</codigoreceptor>
    </recepcion>
    <entrega coste="20" receptor="texto">
        <transportista>T1</transportista>
        <distancia unidad="kilometros">100</distancia>
    </entrega>
</portes>
