=== AntonioMC12/DAM/1º/LM/xml/Boletin4/Ejercicio6/Ejercicio6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="codigo" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1000"></xs:minInclusive>
                            <xs:maxInclusive value="9999"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="direccion" type="xs:string" minOccurs="1"/>
                <xs:element name="telefono" minOccurs="1">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"></xs:pattern>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="propietario">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" minOccurs="1"/>
                            <xs:element name="telefono" minOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="libro">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" minOccurs="1"/>
                            <xs:element name="autor" type="xs:string" minOccurs="1"/>
                            <xs:element name="formato"  minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="RÃºstica"></xs:pattern>
                                        <xs:pattern value="Tapa Dura"></xs:pattern>
                                        <xs:pattern value="Tapa Blanda"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="publicacion" type="xs:integer" minOccurs="0"/>
                            <xs:element name="precio" type="xs:double" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AntonioMC12/DAM/1º/LM/xml/Boletin4/Ejercicio6/Ejercicio6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio6.xsd">
    <codigo>1263</codigo>
    <direccion>Juan de Juni, 31</direccion>
    <telefono>983555555</telefono>
    <propietario>
        <nombre>Juanito</nombre>
        <telefono>656222111</telefono>
    </propietario>
    <libro>
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <formato>Rústica</formato>
        <publicacion>1967</publicacion>
        <precio>23.5</precio>
    </libro>
</libreria>
