=== AntonioMC12/DAM/1º/LM/xml/Boletin4/Ejercicio5/Ejercicio5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="faq">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="info" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="autor" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="version" minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9][.][0-9]"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fecha " type="xs:date" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="part" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="q" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="qtext" type="xs:string"/>
                                        <xs:element name="a" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>    
    </xs:element>
</xs:schema>

=== AntonioMC12/DAM/1º/LM/xml/Boletin4/Ejercicio5/Ejercicio5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<faq xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio5.xsd">
    <info>
        <titulo>WINDOWS98? SOLO SI ME OBLIGAN!</titulo>
        <autor>Fernando Damián Lorenzo García</autor>
        <email>Fer@yahoo.es </email>
        <version>1.0</version>
        <fecha>1999-05-01</fecha>
    </info>
    <part>
        <q>
            <qtext>¿Por qué tengo que instalar W95?</qtext>
            <a> A mi también me parece una buena pregunta.</a>
        </q>
        <q>
            <qtext>Y de que me vale?</qtext>
            <a>Otra ingeniosa pregunta.</a>
        </q>
    </part>
</faq>
